[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/tabris233/lazyvim.git"
  refreshPeriod = "168h"

[".config/tmux/oh-my-tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux.git"
  refreshPeriod = "168h"
